<template>
<el-table
    ref="filterTable"
    :data="tableData"
    style="width: 100%"
    max-height='500px'
    >
    <el-table-column
    prop="id"
    label="序号"
    width="40"
    >
    </el-table-column>
    <el-table-column
    prop="equip_id"
    label="设备编号"
    width="120"
    >
    </el-table-column>
    <el-table-column
    prop="type"
    label="分类"
    width="40"
    >
    </el-table-column>
    <el-table-column
    prop="equip_type"
    label="设备分类">
    </el-table-column>
    <el-table-column
    prop="property"
    label="固定资产编号"
    >
    </el-table-column>
    <el-table-column
    prop="name"
    label="设备名称"
    >
    </el-table-column>
    <el-table-column
    prop="model"
    label="型号"
    >
    </el-table-column>
    <el-table-column
    prop="specification"
    label="规格"
    width='220'
    >
    </el-table-column>
    <el-table-column
    prop="production"
    label="制造商"
    >
    </el-table-column>
    <el-table-column
    prop="description"
    label="设备描述"
    >
    </el-table-column>
    <el-table-column
    prop="location"
    label="安装位置"
    >
    </el-table-column>
    <el-table-column
    prop="out_id"
    label="出厂编号"
    >
    </el-table-column>
    <el-table-column
    prop="service_life"
    label="预计使用年限"
    >
    </el-table-column>
    <el-table-column
    prop="year_of_use"
    label="投用日期(年)"
    >
    </el-table-column>
    <el-table-column
    prop="month_of_use"
    label="投用日期(月)"
    >
    </el-table-column>
    <el-table-column
    prop="status"
    label="状况"
    >
    </el-table-column>
    <el-table-column
    prop="remark"
    label="备注"
    >
    </el-table-column>
    <el-table-column
    prop="last_replace_date"
    label="最近更换日期"
    >
    </el-table-column>
    <el-table-column
    prop="expected_replace_year"
    label="预期更换日期(年)"
    >
    </el-table-column>
    <el-table-column
    prop="expected_replace_month"
    label="预期更换日期(月)"
    >
    </el-table-column>
    <el-table-column
    prop="replace_record"
    label="设备更换记录"
    >
    </el-table-column>
</el-table>
</template>

<script>
export default {
    methods: {
        filterTag(value, row) {
            return row.type === value;
        },
    },
    data() {
    return {
        tableData: [
            {
                id:'1',
                equip_id:'15687686',
                type:'BA',
                equip_type:'传感器',
                property:'无',
                name:'风管温度传感器',
                model:'H8040N0021',
                specification:'传感器元件NTC20K 防护等级IP54 温度范围-40~70℃',
                production:'霍尼韦尔',
                description:'AHU-1-1回风温度',
                location:'主楼1F空调机房',
                out_id:'2021.7.1',
                service_life:'10',
                year_of_use:'2021',
                month_of_use:'7',
                status:'在用',
                remark:'',
                last_replace_date:'2021/7/17',
                expected_replace_year:'2031',
                expected_replace_month:'7',
                replace_record:'2019/7/13'
            },
            {
                id:'2',
                equip_id:'15687686',
                type:'BA',
                equip_type:'传感器',
                property:'无',
                name:'风管温度传感器',
                model:'H8040N0021',
                specification:'传感器元件NTC20K 防护等级IP54 温度范围-40~70℃',
                production:'霍尼韦尔',
                description:'AHU-1-1回风温度',
                location:'主楼1F空调机房',
                out_id:'2021.7.1',
                service_life:'10',
                year_of_use:'2021',
                month_of_use:'7',
                status:'在用',
                remark:'',
                last_replace_date:'2021/7/17',
                expected_replace_year:'2031',
                expected_replace_month:'7',
                replace_record:'2019/7/13'
            },
            {
                id:'3',
                equip_id:'15687686',
                type:'BA',
                equip_type:'传感器',
                property:'无',
                name:'风管温度传感器',
                model:'H8040N0021',
                specification:'传感器元件NTC20K 防护等级IP54 温度范围-40~70℃',
                production:'霍尼韦尔',
                description:'AHU-1-1回风温度',
                location:'主楼1F空调机房',
                out_id:'2021.7.1',
                service_life:'10',
                year_of_use:'2021',
                month_of_use:'7',
                status:'在用',
                remark:'',
                last_replace_date:'2021/7/17',
                expected_replace_year:'2031',
                expected_replace_month:'7',
                replace_record:'2019/7/13'
            },
            {
                id:'4',
                equip_id:'15687686',
                type:'BA',
                equip_type:'传感器',
                property:'无',
                name:'风管温度传感器',
                model:'H8040N0021',
                specification:'传感器元件NTC20K 防护等级IP54 温度范围-40~70℃',
                production:'霍尼韦尔',
                description:'AHU-1-1回风温度',
                location:'主楼1F空调机房',
                out_id:'2021.7.1',
                service_life:'10',
                year_of_use:'2021',
                month_of_use:'7',
                status:'在用',
                remark:'',
                last_replace_date:'2021/7/17',
                expected_replace_year:'2031',
                expected_replace_month:'7',
                replace_record:'2019/7/13'
            },
            {
                id:'5',
                equip_id:'15687686',
                type:'BA',
                equip_type:'传感器',
                property:'无',
                name:'风管温度传感器',
                model:'H8040N0021',
                specification:'传感器元件NTC20K 防护等级IP54 温度范围-40~70℃',
                production:'霍尼韦尔',
                description:'AHU-1-1回风温度',
                location:'主楼1F空调机房',
                out_id:'2021.7.1',
                service_life:'10',
                year_of_use:'2021',
                month_of_use:'7',
                status:'在用',
                remark:'',
                last_replace_date:'2021/7/17',
                expected_replace_year:'2031',
                expected_replace_month:'7',
                replace_record:'2019/7/13'
            },
            {
                id:'6',
                equip_id:'15687686',
                type:'BA',
                equip_type:'传感器',
                property:'无',
                name:'风管温度传感器',
                model:'H8040N0021',
                specification:'传感器元件NTC20K 防护等级IP54 温度范围-40~70℃',
                production:'霍尼韦尔',
                description:'AHU-1-1回风温度',
                location:'主楼1F空调机房',
                out_id:'2021.7.1',
                service_life:'10',
                year_of_use:'2021',
                month_of_use:'7',
                status:'在用',
                remark:'',
                last_replace_date:'2021/7/17',
                expected_replace_year:'2031',
                expected_replace_month:'7',
                replace_record:'2019/7/13'
            },
            {
                id:'7',
                equip_id:'15687686',
                type:'BA',
                equip_type:'传感器',
                property:'无',
                name:'风管温度传感器',
                model:'H8040N0021',
                specification:'传感器元件NTC20K 防护等级IP54 温度范围-40~70℃',
                production:'霍尼韦尔',
                description:'AHU-1-1回风温度',
                location:'主楼1F空调机房',
                out_id:'2021.7.1',
                service_life:'10',
                year_of_use:'2021',
                month_of_use:'7',
                status:'在用',
                remark:'',
                last_replace_date:'2021/7/17',
                expected_replace_year:'2031',
                expected_replace_month:'7',
                replace_record:'2019/7/13'
            },
            {
                id:'8',
                equip_id:'15687686',
                type:'BA',
                equip_type:'传感器',
                property:'无',
                name:'风管温度传感器',
                model:'H8040N0021',
                specification:'传感器元件NTC20K 防护等级IP54 温度范围-40~70℃',
                production:'霍尼韦尔',
                description:'AHU-1-1回风温度',
                location:'主楼1F空调机房',
                out_id:'2021.7.1',
                service_life:'10',
                year_of_use:'2021',
                month_of_use:'7',
                status:'在用',
                remark:'',
                last_replace_date:'2021/7/17',
                expected_replace_year:'2031',
                expected_replace_month:'7',
                replace_record:'2019/7/13'
            },
            
        ]
    }
    }
}
</script>
<style scoped>
    
</style>